In [1]:
import os
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df=pd.read_csv("C://Users//GoD//Desktop//spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
df.shape

(5572, 3)

In [5]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [6]:
df['Spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [18]:
# Split the dataset into training and testing sets
X = df['Message']  # Email text
y = df['Spam']  # Spam or not spam label
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [19]:
X_train.shape

(4457,)

In [20]:
X_test.shape

(1115,)

In [21]:
type(X_train)

pandas.core.series.Series

In [22]:
X_train[:4]

3385    FREE MSG:We billed your mobile number by mista...
3468    URGENT! We are trying to contact U. Todays dra...
4263    You'll never believe this but i have actually ...
3396                                          Then i buy.
Name: Message, dtype: object

In [23]:
type(y_train)

pandas.core.series.Series

In [24]:
y_train[:4]

3385    1
3468    1
4263    0
3396    0
Name: Spam, dtype: int64

In [25]:
X_train.values

array(['FREE MSG:We billed your mobile number by mistake from shortcode 83332.Please call 08081263000 to have charges refunded.This call will be free from a BT landline',
       'URGENT! We are trying to contact U. Todays draw shows that you have won a £800 prize GUARANTEED. Call 09050001808 from land line. Claim M95. Valid12hrs only',
       "You'll never believe this but i have actually got off at taunton. Wow",
       ..., "Neva mind it's ok..",
       'Motivate Behind every darkness, there is a shining light waiting for you to find it... Behind every best friend, there is always trust and love... BSLVYL',
       'I to am looking forward to all the sex cuddling.. Only two more sleeps'],
      dtype=object)

In [26]:
type(X_train.values)

numpy.ndarray

In [27]:
# Create a text vectorizer to convert email text into numerical features
vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train.values)
X_train_vectorized

<4457x7730 sparse matrix of type '<class 'numpy.int64'>'
	with 58841 stored elements in Compressed Sparse Row format>

In [29]:
X_train_vectorized.shape

(4457, 7730)

In [33]:
dir(vectorizer)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [40]:
vectorizer.vocabulary_

{'free': 2964,
 'msg': 4595,
 'we': 7405,
 'billed': 1331,
 'your': 7700,
 'mobile': 4518,
 'number': 4837,
 'by': 1567,
 'mistake': 4495,
 'from': 3001,
 'shortcode': 6092,
 '83332': 648,
 'please': 5211,
 'call': 1583,
 '08081263000': 58,
 'to': 6922,
 'have': 3342,
 'charges': 1716,
 'refunded': 5624,
 'this': 6840,
 'will': 7508,
 'be': 1251,
 'bt': 1514,
 'landline': 3985,
 'urgent': 7193,
 'are': 1029,
 'trying': 7053,
 'contact': 1964,
 'todays': 6930,
 'draw': 2421,
 'shows': 6110,
 'that': 6797,
 'you': 7696,
 'won': 7564,
 '800': 617,
 'prize': 5381,
 'guaranteed': 3247,
 '09050001808': 166,
 'land': 3983,
 'line': 4109,
 'claim': 1806,
 'm95': 4261,
 'valid12hrs': 7233,
 'only': 4918,
 'll': 4140,
 'never': 4736,
 'believe': 1287,
 'but': 1551,
 'actually': 787,
 'got': 3188,
 'off': 4875,
 'at': 1100,
 'taunton': 6703,
 'wow': 7603,
 'then': 6813,
 'buy': 1556,
 'lol': 4163,
 'would': 7599,
 'despite': 2252,
 'these': 6819,
 'cramps': 2039,
 'like': 4097,
 'being': 1286,
 '

In [51]:
#Names of features in vocubulary
vectorizer.get_feature_names_out()[3342]

'have'

In [32]:
vectorizer.get_feature_names_out().shape

(7730,)

In [46]:
#Converting to numpy array
X_train_np = X_train_vectorized.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
import numpy as np
#where the values are not zero
np.where(X_train_np[0]!=0)

(array([  58,  648, 1251, 1331, 1514, 1567, 1583, 1716, 2964, 3001, 3342,
        3985, 4495, 4518, 4595, 4837, 5211, 5624, 6092, 6840, 6922, 7405,
        7508, 7700], dtype=int64),)

In [47]:
X_train[:4]

3385    FREE MSG:We billed your mobile number by mista...
3468    URGENT! We are trying to contact U. Todays dra...
4263    You'll never believe this but i have actually ...
3396                                          Then i buy.
Name: Message, dtype: object

In [48]:
X_train[:4][3385]

'FREE MSG:We billed your mobile number by mistake from shortcode 83332.Please call 08081263000 to have charges refunded.This call will be free from a BT landline'

In [50]:
X_train_np[0][3342]

1

In [52]:
# Train a classifier (Naive Bayes is a common choice for text classification)
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)

MultinomialNB()

In [53]:
X_test_vectorized=vectorizer.transform(X_test)

In [54]:
X_test_vectorized

<1115x7730 sparse matrix of type '<class 'numpy.int64'>'
	with 14203 stored elements in Compressed Sparse Row format>

In [55]:
# Make predictions on the test set
y_pred = classifier.predict(X_test_vectorized)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [56]:
# Evaluate the classifier's performance
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{confusion}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.9865470852017937
Confusion Matrix:
[[953   6]
 [  9 147]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.96      0.94      0.95       156

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [59]:
#Testing
Sample_emails=[
             "Hey Rahul, can we get together to watch football game tomorrow?",
             "Upto 20% Discount on parking,exclusive offer just for you.Don't miss this reward!",
             "My name is Debarpan. I am Associate Software Developer at TCS Pvt.Ltd. I am planning to quit my job and look for building up some start-up business. I am ready to invest but want some Data Analyst and Research Intern who can figure out some unique and great business ideas.Please contact me at +918777563015 and mail me your CV."
]
emails_count=vectorizer.transform(Sample_emails)
classifier.predict(emails_count)

array([0, 1, 0], dtype=int64)

In [60]:
#Classification and transformation through Pipeline
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [61]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [63]:
y_predicted=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       959
           1       0.96      0.94      0.95       156

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

